name: Build

on:
  push:
    branches:
      - 'release-*'

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.python-str }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Window 64 bit
          # Note: windows-2019 is needed for older Python versions:
          # https://github.com/scikit-learn/scikit-learn/issues/22530
          - os: windows-2019
            python-str: 38
            python-version: "3.8"
            platform_id: win_amd64
          - os: windows-latest
            python-str: 39
            python-version: "3.9"
            platform_id: win_amd64
          - os: windows-latest
            python-str: 310
            python-version: "3.10"
            platform_id: win_amd64
          - os: windows-latest
            python-str: 311
            python-version: "3.11"
            platform_id: win_amd64
          - os: windows-latest
            python-str: 312
            python-version: "3.12"
            platform_id: win_amd64
          - os: windows-latest
            python-str: 313
            python-version: "3.13"
            platform_id: win_amd64

          # Linux 64 bit manylinux2014
          - os: ubuntu-latest
            python-str: 38
            python-version: "3.8"
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python-str: 39
            python-version: "3.9"
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
          - os: ubuntu-latest
            python-str: 310
            python-version: "3.10"
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python-str: 311
            python-version: "3.11"
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python-str: 312
            python-version: "3.12"
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python-str: 313
            python-version: "3.13"
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          # MacOS x86_64
          - os: macos-latest
            python-str: 38
            python-version: "3.8"
            platform_id: macosx_x86_64
          - os: macos-latest
            python-str: 39
            python-version: "3.9"
            platform_id: macosx_x86_64
          - os: macos-latest
            python-str: 310
            python-version: "3.10"
            platform_id: macosx_x86_64
          - os: macos-latest
            python-str: 311
            python-version: "3.11"
            platform_id: macosx_x86_64
          - os: macos-latest
            python-str: 312
            python-version: "3.12"
            platform_id: macosx_x86_64
          - os: macos-latest
            python-str: 313
            python-version: "3.13"
            platform_id: macosx_x86_64

          # MacOS arm64
          - os: macos-latest
            python-str: 38
            python-version: "3.8"
            platform_id: macosx_arm64
          - os: macos-latest
            python-str: 39
            python-version: "3.9"
            platform_id: macosx_arm64
          - os: macos-latest
            python-str: 310
            python-version: "3.10"
            platform_id: macosx_arm64
          - os: macos-latest
            python-str: 311
            python-version: "3.11"
            platform_id: macosx_arm64
          - os: macos-latest
            python-str: 312
            python-version: "3.12"
            platform_id: macosx_arm64
          - os: macos-latest
            python-str: 313
            python-version: "3.13"
            platform_id: macosx_arm64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0
      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: pip install -r requirements.txt
          CIBW_BUILD: cp${{ matrix.python-str }}-${{ matrix.platform_id }}
          CIBW_ARCHS: all
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
          MACOSX_DEPLOYMENT_TARGET: 10.15
        run: python -m cibuildwheel --output-dir dist/

    # Build the source distribution under Linux
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build source distribution
        run: python setup.py sdist
      - name: Check source distribution
        run: twine check dist/*.tar.gz
